apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      initContainers:
        - name: init-db
          image: postgres:13
          command:
            [
              "sh", "-c",
              "until psql -h postgres-db -U user -d mydb -c 'SELECT 1;' > /dev/null 2>&1; do echo 'Waiting for PostgreSQL to be ready...'; sleep 5; done; \
              psql -h postgres-db -U user -d mydb -c \"CREATE TABLE IF NOT EXISTS logs (path VARCHAR(255), message TEXT);\"; \
              psql -h postgres-db -U user -d mydb -c \"INSERT INTO logs (path, message) VALUES ('/page1', 'Message for Page 1'), ('/page2', 'Message for Page 2');\""
            ]
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "mydb"
      containers:
        - name: demo-app
          image: ghcr.io/pratchayakc/demo-devsecops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: "postgres-db"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: "user"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_NAME
              value: "mydb"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true  # เพื่อป้องกันไม่ให้ผู้ใช้สามารถเขียนข้อมูลลงใน root filesystem
      securityContext:
        fsGroup: 2000  # ตั้งค่า fsGroup เพื่อให้การเข้าถึงไฟล์ระบบที่ปลอดภัยยิ่งขึ้น

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demo
  name: demo-app-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-app-rolebinding
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: default
    namespace: demo
roleRef:
  kind: Role
  name: demo-app-role
  apiGroup: rbac.authorization.k8s.io
