apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
  namespace: demo
  annotations:
    konghq.com/strip-path: "false"  # ไม่ลบ path จากคำขอ
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix  # จะให้รองรับ path ทุกๆ ที่เริ่มต้นด้วย "/"
            backend:
              service:
                name: demo-service  # ชื่อของ Service ที่เชื่อมต่อกับแอป
                port:
                  number: 80
          - path: /add
            pathType: Exact  # จะรองรับ path /add เท่านั้น
            backend:
              service:
                name: demo-service  # ชื่อของ Service ที่เชื่อมต่อกับแอป
                port:
                  number: 80